### ISSUE TITLE
Error, reading the GuildID

### ISSUE THREAD

**Issue by justBMR** [RickyBhatti/DiscordAPI#6] opened 2024-11-25 23:03 UTC
![image](https://github.com/user-attachments/assets/323b479d-7954-4627-9875-f9e41edf3a84)

Goodnight.
First of all, congratulations on your excellent work on this script as it helps a lot with server permissions.

I wanted to ask you for help with this error. I entered the ace permissions in the server.cfg and configured all the necessary data in the script. Unfortunately, I get this error and cannot use the script. I already tested it with another similar script, using the same ID as my discord (where the TAGS will be read), and in this script, it works perfectly.
Can you help me with the solution to the problem?

Greeting

**Comment by RickyBhatti** [comment] 2024-11-26 00:39
Hi there,

Thanks for the kind words, I'm glad the script has been helpful. :)

The error you're encountering is likely due to misconfiguration with your token. A 401 response typically indicates an authorization issue. Please double-check the following:
- Ensure that the token in your configuration file is valid and correctly entered, with no extra characters or spaces before or after it, and that it is within the quotes.
- Verify that the bot is added to the guild you're attempting to use.

If the issue is still not fixed, share more details in this issue and we can look further.

**Comment by RickyBhatti** [comment] 2024-12-02 06:17
Hey! Just wanted to mention that if no more information is provided within the next couple of days, I'll be closing this issue.

**Comment by RickyBhatti** [comment] 2024-12-03 22:50
Since I haven’t received the requested information (or any update), I'll be closing this for now.

If the issue persists, please feel free to reopen it with the additional details.

**Closed as completed by RickyBhatti** 2024-12-03 22:50 UTC
